title: Previewing your picture with PiCamera
hero_image: images/banner.png
description: Find out how to show a preview of what the camera can see
original_url: 
theme: cc-prototype
duration: 1 # 1, 2 or 3
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "python, picamera"
steps:
  - title: Previewing an image
